# Peer-Graded Recap Matrices

### Part (a)

This matrix is sparce, as most of its elements are zero.

This matrix is also symmetric, as the $(i,j)$ element is the same as the $(j,i)$ element for all $i \neq j$.

### Part (b)

In [8]:
import numpy as np

# Build matrix
nums = [2,1.5,-3,-1,0.5,-0.5]
matrix = np.diag(nums)
print('Matrix:')
print(matrix)
print('\n')

# Get eigenpairs
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print('Eigenvalues:')
print(eigenvalues)
print('\n')
print('Eigenvectors:')
print(eigenvectors)

Matrix:
[[ 2.   0.   0.   0.   0.   0. ]
 [ 0.   1.5  0.   0.   0.   0. ]
 [ 0.   0.  -3.   0.   0.   0. ]
 [ 0.   0.   0.  -1.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0. ]
 [ 0.   0.   0.   0.   0.  -0.5]]


Eigenvalues:
[ 2.   1.5 -3.  -1.   0.5 -0.5]


Eigenvectors:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Shown formulaically, the eigenvalues of the matrix are found as follows:
$$\begin{vmatrix}
2-\lambda & 0 & 0 & 0 & 0 & 0 \\
0 & 1.5-\lambda & 0 & 0 & 0 & 0 \\
0 & 0 & -3-\lambda & 0 & 0 & 0 \\
0 & 0 & 0 & -1-\lambda & 0 & 0 \\
0 & 0 & 0 & 0 & 0.5-\lambda & 0 \\
0 & 0 & 0 & 0 & 0 & 1-\lambda
\end{vmatrix}$$

$$= (2-\lambda)*\begin{vmatrix}
1.5-\lambda & 0 & 0 & 0 & 0 \\
0 & -3-\lambda & 0 & 0 & 0 \\
0 & 0 & -1-\lambda & 0 & 0 \\
0 & 0 & 0 & 0.5-\lambda & 0 \\
0 & 0 & 0 & 0 & 1-\lambda
\end{vmatrix} + 0$$