# Peer-Graded Recap Matrices

### Part (a)

This matrix is sparce, as most of its elements are zero.

This matrix is also symmetric, as the $(i,j)$ element is the same as the $(j,i)$ element for all $i \neq j$.

### Part (b)

In [1]:
import numpy as np

# Build matrix
nums = [2,1.5,-3,-1,0.5,-0.5]
matrix = np.diag(nums)
print('Matrix:')
print(matrix)
print('\n')

# Get eigenpairs
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print('Eigenvalues:')
print(eigenvalues)
print('\n')
print('Eigenvectors:')
print(eigenvectors)

Matrix:
[[ 2.   0.   0.   0.   0.   0. ]
 [ 0.   1.5  0.   0.   0.   0. ]
 [ 0.   0.  -3.   0.   0.   0. ]
 [ 0.   0.   0.  -1.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0. ]
 [ 0.   0.   0.   0.   0.  -0.5]]


Eigenvalues:
[ 2.   1.5 -3.  -1.   0.5 -0.5]


Eigenvectors:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Shown formulaically, the eigenvalues of the matrix are found as follows:
$$\begin{vmatrix}
2-\lambda & 0 & 0 & 0 & 0 & 0 \\
0 & 1.5-\lambda & 0 & 0 & 0 & 0 \\
0 & 0 & -3-\lambda & 0 & 0 & 0 \\
0 & 0 & 0 & -1-\lambda & 0 & 0 \\
0 & 0 & 0 & 0 & 0.5-\lambda & 0 \\
0 & 0 & 0 & 0 & 0 & -0.5-\lambda
\end{vmatrix} = 0$$

$$= (2-\lambda)*\begin{vmatrix}
1.5-\lambda & 0 & 0 & 0 & 0 \\
0 & -3-\lambda & 0 & 0 & 0 \\
0 & 0 & -1-\lambda & 0 & 0 \\
0 & 0 & 0 & 0.5-\lambda & 0 \\
0 & 0 & 0 & 0 & -0.5-\lambda
\end{vmatrix} - 0 = 0$$

$$= (2-\lambda)*(1.5-\lambda)*\begin{vmatrix}
-3-\lambda & 0 & 0 & 0 \\
0 & -1-\lambda & 0 & 0 \\
0 & 0 & 0.5-\lambda & 0 \\
0 & 0 & 0 & -0.5-\lambda
\end{vmatrix} - 0 = 0$$

$$= (2-\lambda)*(1.5-\lambda)*(-3-\lambda)*\begin{vmatrix}
-1-\lambda & 0 & 0 \\
0 & 0.5-\lambda & 0 \\
0 & 0 & -0.5-\lambda
\end{vmatrix} - 0 = 0$$

$$= (2-\lambda)*(1.5-\lambda)*(-3-\lambda)*(-1-\lambda)*\begin{vmatrix}
0.5-\lambda & 0 \\
0 & -0.5-\lambda
\end{vmatrix} - 0 = 0$$

$$= (2-\lambda)*(1.5-\lambda)*(-3-\lambda)*(-1-\lambda)*(0.5-\lambda)*(-0.5-\lambda) = 0$$

This final equation shows that the possible solutions for $\lambda$ are 2, 1.5, -3, -1, 0.5, -0.5.

Taking $\lambda = 2$ for an example, we can find the corresponding eigenvector as follows:
$$Av = \lambda v$$

$$\begin{bmatrix}
2 & 0 & 0 & 0 & 0 & 0 \\
0 & 1.5 & 0 & 0 & 0 & 0 \\
0 & 0 & -3 & 0 & 0 & 0 \\
0 & 0 & 0 & -1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0.5 & 0 \\
0 & 0 & 0 & 0 & 0 & -0.5
\end{bmatrix}
\begin{bmatrix}
a \\
b \\
c \\
d \\
e \\
f
\end{bmatrix} = 2
\begin{bmatrix}
a \\
b \\
c \\
d \\
e \\
f
\end{bmatrix}$$

$$= 2 \begin{bmatrix}
1 \\
0 \\
0 \\
0 \\
0 \\
0
\end{bmatrix}$$

Thus we find an eigenvector of $\lambda = 2$ to be $= \begin{bmatrix}
1 \\
0 \\
0 \\
0 \\
0 \\
0
\end{bmatrix}$

This logic can be extended to the other eigenvalues following this same process. The eigenvalue listed on the $j^{th}$ column of the original matrix diagonal will have a corresponding eigenvector that has an element 1 in the $j^{th}$ row of the vector, with zeroes in all other rows.


### Part(c)

The Frobenius norm $||A||$ is found as $\sqrt{\sum_{ij} A_{ij}^2}$
$$= \sqrt{2^2 + 1.5^2 + (-3)^2 + (-1)^2 + 0.5^2 + (-0.5)^2} = 4.093$$

We know that a singular value is the absolute value of an eigenvalue, and the operator norm is the largest singular value. Thus, for this matrix, the operator norm is 3.

For this matrix, the nuclear norm is the sum of the absolute values of the eigenvalues, which is $2+1.5+3+1+0.5+0.5 = 8.5$

### Part(d)

The largest eigenvalue from Part (b) is 2. The operator norm is 3. So the largest eigenvalue does not equal the operator norm. The operator norm is equal to the largest *absolute value* eigenvalue.